import { NextResponse } from "next/server";
import { getOptionalUser } from "../auth";
import { logEvent } from "../observability";

export class TradingAccessError extends Error {
  constructor() {
    super("FORBIDDEN");
  }
}

export async function requireTradingOwner() {
  const user = await getOptionalUser();
  if (!user || user.role !== "SUPER_ADMIN") {
    if (user) logEvent("trading_access_denied", { userId: user.id, role: user.role });
    throw new TradingAccessError();
  }
  return user;
}

export function tradingForbidden() {
  return NextResponse.json({ error: "FORBIDDEN" }, { status: 403 });
}

const CLIENT_ERROR_STATUS: Record<string, number> = {
  INVALID_JSON: 400,
  INVALID_ALLOCATION_AMOUNT: 400,
  ALLOCATION_MUST_BE_WHOLE_USD: 400,
  ALLOCATION_BELOW_MINIMUM: 400,
  ALLOCATION_ABOVE_MAXIMUM: 400,
  IDEMPOTENCY_KEY_REQUIRED: 400,
  OWNER_WALLET_NOT_FOUND: 404,
  ALLOCATION_NOT_FOUND: 404,
  INSUFFICIENT_POINTS: 409,
  IDEMPOTENCY_KEY_CONFLICT: 409,
  ALLOCATION_ALREADY_RELEASED: 409,
  ALLOCATION_IN_USE: 409,
  INSUFFICIENT_TRADING_BALANCE: 409,
  INVALID_RISK_CONFIG: 400,
  INVALID_SHARIAH_INPUT: 400,
  INVALID_CONTROL_ACTION: 400,
  INVALID_CIRCUIT_BREAKER_REASON: 400,
  CONFIRMATION_REQUIRED: 400,
  SHARIAH_POLICY_NOT_FOUND: 409,
  INVALID_APPROVAL_INPUT: 400,
  APPROVAL_NOT_FOUND: 404,
  APPROVAL_RISK_SNAPSHOT_REQUIRED: 409,
  INVALID_APPROVAL_RISK_SNAPSHOT: 409,
  INVALID_APPROVAL_AMOUNT: 400,
  APPROVAL_AMOUNT_MISMATCH: 409,
  OWNER_APPROVAL_NOT_CONSUMED: 409,
  APPROVAL_EXPIRED: 409,
  SHARIAH_APPROVAL_REQUIRED: 409,
  INVALID_OPPORTUNITY_STRATEGY: 400,
  NO_BUY_SIGNAL: 409,
  STOP_LOSS_REQUIRED: 409,
  INVALID_TAKE_PROFIT_FOR_BUY: 400,
  PAPER_TRADING_RISK_CONFIG_REQUIRED: 409,
  INVALID_TESTNET_EXECUTION_IDENTITY: 400,
  INVALID_TESTNET_EXECUTION_STRATEGY: 400,
  TESTNET_EXECUTION_PLAN_REQUIRED: 409,
  BINANCE_TESTNET_API_CREDENTIALS_REQUIRED: 503,
  BINANCE_TESTNET_RESTRICTED_LOCATION: 503,
  BINANCE_TESTNET_NETWORK_ERROR: 503,
  BINANCE_TESTNET_INVALID_RESPONSE: 502,
  BINANCE_TESTNET_TRADING_DISABLED: 409,
  BINANCE_TESTNET_WITHDRAWALS_MUST_BE_DISABLED: 409,
  BINANCE_TESTNET_SPOT_PERMISSION_REQUIRED: 409,
  BINANCE_TESTNET_ORDER_NOT_CONFIRMED: 502,
  INVALID_BINANCE_TESTNET_BASE_URL: 500,
  BINANCE_TESTNET_BASE_URL_MUST_BE_OFFICIAL_TESTNET: 500,
  INVALID_BINANCE_TESTNET_RECV_WINDOW: 500,
  INVALID_BINANCE_TESTNET_CLIENT_ORDER_ID: 400,
  INVALID_BINANCE_TESTNET_SYMBOL: 400,
  INVALID_BINANCE_TESTNET_ORDER_RESPONSE: 502,
  INVALID_BINANCE_TESTNET_ACCOUNT_RESPONSE: 502,
  BINANCE_TESTNET_ORDER_NOT_FILLED: 409,
  BINANCE_LIVE_API_CREDENTIALS_REQUIRED: 503,
  BINANCE_LIVE_RESTRICTED_LOCATION: 503,
  BINANCE_LIVE_NETWORK_ERROR: 503,
  BINANCE_LIVE_INVALID_RESPONSE: 502,
  BINANCE_LIVE_SPOT_ACCOUNT_REQUIRED: 409,
  BINANCE_LIVE_SPOT_TRADING_REQUIRED: 409,
  BINANCE_LIVE_WITHDRAWALS_MUST_BE_DISABLED: 409,
  BINANCE_LIVE_MARGIN_MUST_BE_DISABLED: 409,
  BINANCE_LIVE_FUTURES_MUST_BE_DISABLED: 409,
  BINANCE_LIVE_OPTIONS_MUST_BE_DISABLED: 409,
  BINANCE_LIVE_PORTFOLIO_MARGIN_MUST_BE_DISABLED: 409,
  BINANCE_LIVE_INTERNAL_TRANSFER_MUST_BE_DISABLED: 409,
  GAMEVORTEX_LIVE_TRADING_DISABLED: 409,
};

export function tradingErrorStatus(message: string): number | null {
  return CLIENT_ERROR_STATUS[message] ?? null;
}
