import { NextRequest, NextResponse } from "next/server";
import {
  handleUpload,
  type HandleUploadBody,
} from "@vercel/blob/client";
import { getOptionalUser } from "@/lib/auth";
import {
  WALLPAPER_IMAGE_MIME_TYPES,
  WALLPAPER_MAX_FILE_SIZE,
} from "@/lib/wallpaper-storage";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function POST(request: NextRequest) {
  try {
    /*
     * ------------------------------------------------------------
     * 1. Verify Blob configuration before doing anything else.
     * ------------------------------------------------------------
     *
     * The token must exist on the server.
     * It must NEVER be exposed to the browser.
     */
    const blobToken =
      process.env.BLOB_READ_WRITE_TOKEN?.trim();

    if (!blobToken) {
      console.error(
        "Wallpaper upload configuration error: BLOB_READ_WRITE_TOKEN is missing.",
      );

      return NextResponse.json(
        {
          success: false,
          error:
            "Vercel Blob غير مهيأ بشكل صحيح. BLOB_READ_WRITE_TOKEN غير موجود في بيئة Production.",
        },
        { status: 500 },
      );
    }

    /*
     * ------------------------------------------------------------
     * 2. Parse the request body.
     * ------------------------------------------------------------
     */
    let body: HandleUploadBody;

    try {
      body =
        (await request.json()) as HandleUploadBody;
    } catch (error) {
      console.error(
        "Wallpaper upload request body parsing failed:",
        error,
      );

      return NextResponse.json(
        {
          success: false,
          error:
            "بيانات رفع الصورة غير صالحة.",
        },
        { status: 400 },
      );
    }

    /*
     * ------------------------------------------------------------
     * 3. Generate the Vercel Blob client token.
     * ------------------------------------------------------------
     */
    const response = await handleUpload({
      token: blobToken,

      request,

      body,

      /*
       * This callback is executed when the browser requests
       * permission to upload a file.
       */
      onBeforeGenerateToken:
        async (pathname) => {
          /*
           * ------------------------------------------------------
           * Authentication
           * ------------------------------------------------------
           *
           * Only SUPER_ADMIN may generate wallpaper upload tokens.
           */
          const user =
            await getOptionalUser();

          if (
            !user ||
            user.role !== "SUPER_ADMIN"
          ) {
            console.warn(
              "Unauthorized wallpaper upload token request.",
            );

            throw new Error(
              "UNAUTHORIZED",
            );
          }

          /*
           * ------------------------------------------------------
           * Validate upload path
           * ------------------------------------------------------
           */
          if (
            typeof pathname !==
              "string" ||
            !pathname.startsWith(
              "wallpapers/",
            ) ||
            pathname.includes(
              "..",
            )
          ) {
            console.warn(
              "Invalid wallpaper upload pathname:",
              pathname,
            );

            throw new Error(
              "INVALID_WALLPAPER_UPLOAD_PATH",
            );
          }

          /*
           * ------------------------------------------------------
           * Return upload restrictions
           * ------------------------------------------------------
           */
          return {
            allowedContentTypes: [
              ...WALLPAPER_IMAGE_MIME_TYPES,
            ],

            maximumSizeInBytes:
              WALLPAPER_MAX_FILE_SIZE,

            addRandomSuffix: true,
          };
        },

      /*
       * ----------------------------------------------------------
       * Upload completed callback
       * ----------------------------------------------------------
       *
       * Database creation intentionally remains in:
       *
       * /api/admin/wallpapers
       *
       * The upload endpoint is responsible only for authorizing
       * and completing the Blob upload handshake.
       */
      onUploadCompleted:
        async () => {
          console.log(
            "Wallpaper Blob upload completed.",
          );
        },
    });

    /*
     * ------------------------------------------------------------
     * 4. Return the response generated by Vercel Blob.
     * ------------------------------------------------------------
     */
    return NextResponse.json(
      response,
      { status: 200 },
    );
  } catch (error) {
    /*
     * ------------------------------------------------------------
     * 5. Detailed server-side error logging
     * ------------------------------------------------------------
     */
    console.error(
      "Wallpaper Blob upload handshake failed:",
      error,
    );

    const message =
      error instanceof Error
        ? error.message
        : "Unknown upload authorization error";

    /*
     * Authentication failure
     */
    if (
      message ===
      "UNAUTHORIZED"
    ) {
      return NextResponse.json(
        {
          success: false,
          error:
            "غير مصرح لك برفع الخلفيات.",
        },
        { status: 401 },
      );
    }

    /*
     * Invalid pathname
     */
    if (
      message ===
      "INVALID_WALLPAPER_UPLOAD_PATH"
    ) {
      return NextResponse.json(
        {
          success: false,
          error:
            "مسار رفع الخلفية غير صالح.",
        },
        { status: 400 },
      );
    }

    /*
     * Generic Blob/configuration error
     */
    return NextResponse.json(
      {
        success: false,
        error:
          "فشل إنشاء تصريح رفع الصورة إلى Vercel Blob.",
      },
      { status: 500 },
    );
  }
}
