import Link from "next/link";
import { getOwnerOrAccessScreen } from "@/lib/admin-access";
import { db } from "@/lib/prisma";
export const dynamic="force-dynamic";
export default async function ContentHealth(){const gate=await getOwnerOrAccessScreen();if("screen" in gate)return gate.screen;const [games,apps,publishedGames,publishedApps,uncategorizedGames,uncategorizedApps,unplatformedGames,unplatformedApps,missingGameSources,missingAppSources,duplicateGameGroups,duplicateAppGroups]=await Promise.all([db.game.count(),db.app.count(),db.game.count({where:{published:true}}),db.app.count({where:{published:true}}),db.game.count({where:{gameCategories:{none:{}}}}),db.app.count({where:{appCategories:{none:{}}}}),db.game.count({where:{gamePlatforms:{none:{}}}}),db.app.count({where:{appPlatforms:{none:{}}}}),db.game.count({where:{published:true,officialUrl:null}}),db.app.count({where:{published:true,officialUrl:null}}),db.game.groupBy({by:["titleEn"],where:{published:true},_count:{titleEn:true},having:{titleEn:{_count:{gt:1}}}}),db.app.groupBy({by:["nameEn"],where:{published:true},_count:{nameEn:true},having:{nameEn:{_count:{gt:1}}}})]);
const duplicateGamesCount=duplicateGameGroups.reduce((sum,g)=>sum+g._count.titleEn,0);
const duplicateAppsCount=duplicateAppGroups.reduce((sum,g)=>sum+g._count.nameEn,0);
const unpublishedGames=games-publishedGames;
const unpublishedApps=apps-publishedApps;
return <main className="wrap"><section className="glass hero"><Link href="/admin">← لوحة الإدارة</Link><h1>Content Health</h1><p className="muted">فحص بنيوي للمحتوى قبل اعتباره جاهزًا للنشر.</p></section><section className="grid"><Metric t="إجمالي الألعاب" n={games}/><Metric t="إجمالي التطبيقات" n={apps}/><Metric t="ألعاب منشورة" n={publishedGames}/><Metric t="تطبيقات منشورة" n={publishedApps}/><Metric t="ألعاب غير منشورة" n={unpublishedGames}/><Metric t="تطبيقات غير منشورة" n={unpublishedApps}/><Metric t="ألعاب بلا تصنيف" n={uncategorizedGames} bad={uncategorizedGames>0}/><Metric t="تطبيقات بلا تصنيف" n={uncategorizedApps} bad={uncategorizedApps>0}/><Metric t="ألعاب بلا منصة" n={unplatformedGames} bad={unplatformedGames>0}/><Metric t="تطبيقات بلا منصة" n={unplatformedApps} bad={unplatformedApps>0}/><Metric t="ألعاب منشورة بلا مصدر" n={missingGameSources} bad={missingGameSources>0}/><Metric t="تطبيقات منشورة بلا مصدر" n={missingAppSources} bad={missingAppSources>0}/><Metric t="ألعاب مكررة الاسم" n={duplicateGamesCount} bad={duplicateGamesCount>0}/><Metric t="تطبيقات مكررة الاسم" n={duplicateAppsCount} bad={duplicateAppsCount>0}/></section>{(duplicateGameGroups.length>0||duplicateAppGroups.length>0)&&<section className="glass card"><h2>تفاصيل التكرار (للمراجعة اليدوية فقط)</h2>{duplicateGameGroups.length>0&&<><h3>ألعاب</h3><ul>{duplicateGameGroups.map(g=><li key={g.titleEn}>{g.titleEn} — {g._count.titleEn} نسخ</li>)}</ul></>}{duplicateAppGroups.length>0&&<><h3>تطبيقات</h3><ul>{duplicateAppGroups.map(a=><li key={a.nameEn}>{a.nameEn} — {a._count.nameEn} نسخ</li>)}</ul></>}<p className="muted">هذه القائمة للمراجعة فقط، لا يتم حذف أو دمج أي عنصر تلقائيًا.</p></section>}<section className="glass card"><h2>قواعد النشر</h2><ul><li>لا تُنشَر لعبة أو تطبيق بلا مصدر رسمي موثوق.</li><li>لا يُسمح بخلط التطبيق مع الألعاب.</li><li>كل عنصر منشور يجب أن يملك منصة وتصنيفًا مناسبين.</li><li>لا نُنشئ تقييمات أو تحميلات أو أسعارًا وهمية.</li></ul></section></main>}
function Metric({t,n,bad=false}:{t:string;n:number;bad?:boolean}){return <article className="glass card"><span className="muted">{t}</span><strong style={{display:"block",fontSize:32,marginTop:8,color:bad?"#ff7b9c":"inherit"}}>{n}</strong></article>}
