import { z } from "zod";

import { getOptionalUser } from "@/lib/auth";

export type AiToolUser = {
  id: string;
  role: string;
};

export type AiToolContext = {
  user: AiToolUser;
};

export class AiToolError extends Error {
  readonly code: string;
  readonly status: number;

  constructor(
    code: string,
    message: string,
    status = 400,
  ) {
    super(message);
    this.name = "AiToolError";
    this.code = code;
    this.status = status;
  }
}

/**
 * Requires an authenticated GameVortex user before
 * any AI Tool can access application data.
 */
export async function requireAiToolUser(): Promise<AiToolContext> {
  const user = await getOptionalUser();

  if (!user) {
    throw new AiToolError(
      "UNAUTHORIZED",
      "Authentication is required to use this GameVortex AI tool.",
      401,
    );
  }

  return {
    user: {
      id: user.id,
      role: user.role,
    },
  };
}

/**
 * Authorization helper for tools that need specific roles.
 *
 * This is server-side authorization.
 * Never rely on UI visibility or AI instructions for permissions.
 */
export function requireAiToolRole(
  context: AiToolContext,
  allowedRoles: readonly string[],
): void {
  if (!allowedRoles.includes(context.user.role)) {
    throw new AiToolError(
      "FORBIDDEN",
      "You are not authorized to use this GameVortex AI tool.",
      403,
    );
  }
}

/**
 * Ensures a resource belongs to the authenticated user.
 *
 * This is intentionally simple and will be used by
 * user-scoped tools such as searchLibrary.
 */
export function assertAiToolOwner(
  context: AiToolContext,
  resourceUserId: string,
): void {
  if (context.user.id !== resourceUserId) {
    throw new AiToolError(
      "FORBIDDEN",
      "You are not authorized to access this resource.",
      403,
    );
  }
}

/**
 * Safely parses Tool input.
 *
 * Tools must never trust arguments generated by the AI.
 */
export function parseAiToolInput<T extends z.ZodTypeAny>(
  schema: T,
  input: unknown,
): z.infer<T> {
  const result = schema.safeParse(input);

  if (!result.success) {
    throw new AiToolError(
      "INVALID_TOOL_INPUT",
      "The AI tool received invalid input.",
      400,
    );
  }

  return result.data;
}

/**
 * Common bounded pagination schema.
 *
 * Prevents an AI Tool from requesting huge database result sets.
 */
export const aiToolPaginationSchema = z.object({
  page: z
    .number()
    .int()
    .min(1)
    .max(1000)
    .default(1),

  limit: z
    .number()
    .int()
    .min(1)
    .max(25)
    .default(10),
});

export type AiToolPagination = z.infer<
  typeof aiToolPaginationSchema
>;

/**
 * Converts pagination values into Prisma skip/take values.
 */
export function getAiToolPagination(
  pagination: AiToolPagination,
): {
  skip: number;
  take: number;
} {
  return {
    skip: (pagination.page - 1) * pagination.limit,
    take: pagination.limit,
  };
}

/**
 * Creates a safe Tool response.
 *
 * Tool results should contain only data intentionally selected
 * by the Tool implementation.
 */
export function aiToolResult<T>(
  data: T,
  meta?: Record<string, unknown>,
): {
  ok: true;
  data: T;
  meta?: Record<string, unknown>;
} {
  return {
    ok: true,
    data,
    ...(meta ? { meta } : {}),
  };
}

/**
 * Converts known Tool errors into a predictable result.
 *
 * The AI should receive a controlled error rather than
 * database/provider/internal implementation details.
 */
export function aiToolErrorResult(
  error: unknown,
): {
  ok: false;
  error: {
    code: string;
    message: string;
  };
} {
  if (error instanceof AiToolError) {
    return {
      ok: false,
      error: {
        code: error.code,
        message: error.message,
      },
    };
  }

  console.error("AI_TOOL_INTERNAL_ERROR", error);

  return {
    ok: false,
    error: {
      code: "TOOL_INTERNAL_ERROR",
      message: "The GameVortex AI tool could not complete the request.",
    },
  };
}

/**
 * Normalizes a search string before it reaches Prisma.
 *
 * This is not a security boundary by itself.
 * Prisma parameterization remains the actual database safety layer.
 */
export function normalizeAiToolSearch(
  value: string,
): string {
  return value
    .trim()
    .replace(/\s+/g, " ")
    .slice(0, 100);
}

/**
 * Validates a GameVortex identifier.
 *
 * Prisma IDs in this project use cuid().
 */
export const aiToolIdSchema = z
  .string()
  .trim()
  .min(1)
  .max(64)
  .regex(
    /^[a-zA-Z0-9_-]+$/,
    "Invalid identifier.",
  );

/**
 * Validates a GameVortex slug.
 */
export const aiToolSlugSchema = z
  .string()
  .trim()
  .min(1)
  .max(120)
  .regex(
    /^[a-zA-Z0-9_-]+$/,
    "Invalid slug.",
  );
